### ISSUE TITLE
[AVM Module Issue]: Cannot associate more than a single VM

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/terraform-azurerm-avm-ptn-avd-lza-insights#52]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.1

### Description

https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights/blob/main/main.tf#L228-L229

Only a single association is created. From what I can tell, 

`monitor_data_collection_rule_association_target_resource_id` should be replaced by `monitor_data_collection_rule_association_target_resource_ids` which creates an association for_each object. This way multiple vm-hosts in a host pool can alle be associated to the same rule, as the AVDI configuration workbook in the azure portal only allows selecting a single DCR as a data source to display.

**Comment by jensheerin** [comment]
@audunsolemdal, Thank you for raising the issues. Fixes will be applied in PR #56
