### ISSUE TITLE
[AVM Module Issue]: name must start with specific naming microsoft-avdi-*

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/terraform-azurerm-avm-ptn-avd-lza-insights#53]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.1

### Description

The AVDI configuration workbook in the azure portal currently only displays DCRs which start with `microsoft-avdi-`
https://github.com/microsoft/Application-Insights-Workbooks/blob/fa1b9fbf60f1c2e572a0d31ccae9b3c92666a652/Workbooks/Windows%20Virtual%20Desktop/CheckAMAConfiguration/CheckAMAConfiguration.workbook#L1214

In essence, the `name` variable in the module should be coded to always start with this

**Comment by jensheerin** [comment]
@audunsolemdal, 
Thank you for raising the issues! You are correct DCRs which start with microsoft-avdi- is only allowed for AVD Insights. Hence the sample name. I have added the validation to the code. Fixes will be applied in PR #56

**Comment by jensheerin** [comment]
Fixes applied in PR #56
