### ISSUE TITLE
[AVM Module Issue]: Support azurerm >4.0.0

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/terraform-azurerm-avm-ptn-avd-lza-insights#60]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.2

### Description

Currently the azurerm provider is constrained to `>= 3.71.0, < 4.0.0`

My org is currently migrating to azurerm 4.x and this is putting a blocker.

I would propose that the constraint is changed to < 5.0.0

**Comment by jensheerin** [comment]
@audunsolemdal, thank you for opening issue. 4.0.0 testing is currently in progress and once completed the constraints will be adjusted.

**Comment by jensheerin** [comment]
#62 added the subscription id requirement for version 4.0.0. Thank you again for the issue.

**Comment by audunsolemdal** [comment]
> #62 added the subscription id requirement for version 4.0.0. Thank you again for the issue.

Okay, but seems like the constraint in version 0.1.3 is still hindering me from using the module with azurerm 4.x
https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights/blob/main/terraform.tf#L3-L7

**Comment by jensheerin** [comment]
@audunsolemdal, thank you for following up. It is fixed now. There was a typo on the digit.
