### ISSUE TITLE
[AVM Module Issue]: Diagnostic settings issues

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/terraform-azurerm-avm-ptn-avd-lza-insights#72]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Please see the feedback from one of the customer 

"In this module for AVD insights deployment, we see the variables.tf file has a variable defined for diagnostic_settings and expectation is that, when we call this module with Diagnostic setting specific values defined, the diagnostic setting should be enabled for that specific resource but that does not happen. On checking, we found the main.tf file for this module does not have a resource block needed for creation of the Diagnostic setting which is required"

**Comment by cshea-msft** [comment]
@PmeshramPM  The insights pattern module is to create AVD Insights which is the workbook configuration for monitoring and your setting the diagnostic settings in the management plane pattern. If you look at the main.tf in the managementplane module you can see that it has diagnostic settings enabled

cc @jensheerin

**Comment by jensheerin** [comment]
closing issue answered above. The diagnostic setting is set at on each resource.
