### ISSUE TITLE
[AVM Module Issue]: Support azurerm >4.0.0 in 0.1.3

### ISSUE THREAD

**Issue by nicksp555** [Azure/terraform-azurerm-avm-ptn-avd-lza-insights#82]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.3

### Description

Azurerm 4.x support is not available in 0.1.3 release.

1. Download `https://github.com/Azure/terraform-azurerm-avm-ptn-avd-lza-insights/archive/refs/tags/v0.1.3.zip` (terraform-azurerm-avm-ptn-avd-lza-insights-0.1.3)
2. View ./terraform.tf
required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71.0, < 4.0.0"
    }
Expected version = ">= 3.71.0, < **5**.0.0"

**Comment by jensheerin** [comment]
Fix in 0.1.3
